#!/bin/bash -e

export LC_ALL=C

mkdir -v src.collect/
 
find src/ -mindepth 1 -type d -exec mkdir -pv src.collect/{} \;
find src/ -mindepth 1 -type f -exec install-scripts/python-wrapper {} \;

rm -rfv src/
mv -v src.collect/src/ src/
rm -rf src.collect/
